# Example Configuration File for Confluence RAG System
# Copy this file to config.yaml and fill in your actual values

# Confluence Configuration
confluence:
  base_url: "https://your-domain.atlassian.net"  # Replace with your Confluence URL
  username: "your-email@domain.com"              # Replace with your email
  api_token: "your-api-token-here"               # Replace with your API token
  space_key: "SPACE"                             # Replace with your space key
  
# LLM Configuration
llm:
  endpoint: "http://localhost:11434/api/generate"  # Ollama endpoint (default)
  # Alternative endpoints:
  # endpoint: "http://localhost:8000/v1/chat/completions"  # Local OpenAI-compatible
  # endpoint: "https://api.openai.com/v1/chat/completions"  # OpenAI (requires API key)
  model: "llama2"                                 # Model name
  temperature: 0.7                                # Response randomness (0.0-1.0)
  max_tokens: 2048                                # Maximum response length
  
# Vector Database Configuration
vector_db:
  path: "./vector_db"                             # Local path for vector database
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"  # Fast, good quality
  # Alternative models:
  # embedding_model: "sentence-transformers/all-mpnet-base-v2"  # Better quality, slower
  # embedding_model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"  # Multilingual
  chunk_size: 1000                                # Size of text chunks
  chunk_overlap: 200                              # Overlap between chunks
  
# RAG Configuration
rag:
  top_k: 5                                        # Number of similar chunks to retrieve
  similarity_threshold: 0.7                       # Minimum similarity score (0.0-1.0)
